version: 2
jobs:
  build:
    working_directory: /go/src/github.com/reginleiff/go-tic-tac-toe
    docker: 
        - image: reginleiff/hb-go:latest
    steps:
        - checkout
        - run:
            name: Run Go tests
            command: go test -v #./...
        - setup_remote_docker:
            docker_layer_caching: true
        - run:
            name: Install Docker client
            command: |
              set -x
              VER="17.03.0-ce"
              curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin
        - run: 
            name: Build and push Docker image to Registry
            command: |
              TAG=1.$CIRCLE_BUILD_NUM
              docker build -t reginleiff/gottt:$TAG .      
              docker tag reginleiff/gottt:$TAG reginleiff/gottt:latest
              docker login -u $docker_user -p $docker_pass         
              docker push reginleiff/gottt

