// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Boards  string
	Players string
	Rooms   string
	Tiles   string
}{
	Boards:  "boards",
	Players: "players",
	Rooms:   "rooms",
	Tiles:   "tiles",
}
